### ISSUE TITLE
Mise en place des modèles

### ISSUE THREAD

**Issue by Ozurah** [HE-Arc/Giraffe-Palladium#14]

**Comment by Ozurah** [comment]
Modèles créés dans la branche du commit e1188e8
- [x] Item
- [x] Ask
- [x] Share

**Comment by Ozurah** [comment]
2 points à confirmer avant de créé une pull-request :

# 1 Nom des Foreign-Key
Est-ce que nous
1. Conservons les noms initiaux des foreign key que nous avions spécifié dans le [schéma de la DB](https://github.com/HE-Arc/Giraffe-Palladium/wiki/Schemas#diagramme-de-la-base-de-donn%C3%A9e)
2. Utilisons les nomsautomatiquement généré par Laravel
3. Conservons les noms initiaux, mais nous y rajoutons `_id`

Actuellement, les migrations faites correspondent à ceci (généré avec PhpMyAdmin)
![DB Générée](https://user-images.githubusercontent.com/80265286/200926014-28306e02-96b6-4658-b67c-5497f23b5b93.png)

Les entrées concernées sont :
table | schéma initial | généré par laravel | initial + `_id`
--|--|--|--
asks | borrower | user_id | borrower_id
asks | item | item_id | item_id
items | owner | user_id | owner_id
shares | item | item_id | item_id
shares | lender | -[^1] | lender_id
shares | borrower | -[^1] | borrower_id

[^1]: pour le shares.lender et borrower, ils ont été nommés étant donné que les deux pointes sur la même table

# 2 Contraintes pour Shares

Est-ce qu'on applique les contraintes pour les "nonuser" sur la BdD, ou uniquement une vérification coté code.

Les contraintes seraient : 
- Si `lender` est saisie, `nonuser_lender` est null, et inversément
- Idem pour `borrower` et `nonuser_borrower`
- `lender` et `borrower` peuvent être null, mais pas les deux en même temps

(ajouter des contraintes dans Laravel : [StackOverflow](https://stackoverflow.com/questions/42498585/how-to-add-a-constraint-to-a-table-with-laravels-migrations))

**Comment by Xstoudi** [comment]
Pour les foreign keys: convention over configuration donc option 2.

> pour le shares.lender et borrower, ils ont été nommés étant donné que les deux pointes sur la même table
Qu'entendus par là ? Idem, imo on suit la convention Laravel même pour ces deux-ci.

Par contre petite remarque : le concept de nonuser va être vraiment prise de tête vu qu'il faudra les gérer avec une "flux" différent : pas de ask, par exemple.
