### ISSUE TITLE
Accès un objet sans être connecté

### ISSUE THREAD

**Issue by Ozurah** [HE-Arc/Giraffe-Palladium#34]
Accéder à un objet sans être connecté provoque une exception

Exemple : cliquer sur l'objet calculator :
![image](https://user-images.githubusercontent.com/80265286/205503320-409c3f79-49be-4509-bf25-ebd3e0e0e57d.png)

![image](https://user-images.githubusercontent.com/80265286/205503237-4958df85-97ec-4424-8b3b-c6bb642f5e83.png)

**Comment by Xstoudi** [comment]
Ca doit être réglé sur la branche de la PR #33
