### ISSUE TITLE
Modifications pour l'édition d'un objet

### ISSUE THREAD

**Issue by Ozurah** [HE-Arc/Giraffe-Palladium#48]
- Pour la modification d'un objet, il manque l'option "listé" (pour qu'il apparaisse dans la liste de tous les objets empruntables).
- Les valeurs des boutons sont en anglais (contre le français pour les autres).

![image](https://user-images.githubusercontent.com/80265286/207128783-8bcd8154-a34a-4110-b5c9-e5061445dc0f.png)

**Comment by Ozurah** [comment]
Quand un utilisateur affiche la page d'un objet, et qu'il n'est pas empruntable :
- je met un "bouton gris" (pour garder le flow des boutons "demander/annuler") (même si c'est pas un réel bouton, comme il est désactivé)
- ou une alerte (prend toute la largeur, je trouve moyen)

(fenêtre de droite, j'ai mis les 2 designs)
![image](https://user-images.githubusercontent.com/80265286/207931362-26a5d5f8-fb4c-40db-931b-11eb725e7e0f.png)

**Comment by Xstoudi** [comment]
Le bouton je préfère pour toutes les raisons que t'as évoqué.
