### ISSUE TITLE
Accepter ou refuser une demande d'emprunt

### ISSUE THREAD

**Issue by Xstoudi** [HE-Arc/Giraffe-Palladium#5]

**Comment by seba-chappuis** [comment]
Question importante : la deadline lors de l'emprunt d'un objet est défini par l'emprunteur (en faisant la demande d'emprunt), ou par le proprio de l'objet (lors de l'acceptation de la demande) ?

D'après la maquette, c'est l'emprunteur qui défini ça, mais d'après le schéma de la base de données, il n'y a pas de deadline dans la table `Asks`

**Comment by Xstoudi** [comment]
Regarde ta base de données avec les migrations, il y passablement de trucs qui ont changé de ce côté.
Pour te répondre, la demande d'emprunt ne contient rien, c'est juste une notification vide "hey, cet objet m'intéresse", donc c'est le créancier qui définira quand il veut récupérer son objet (dans le share).

**Comment by Ozurah** [comment]
Pour moi, c'est la personne qui valide l'emprunt qui détermine la deadline (on peut imaginer qu'ils l'ont conclus (oral, discord, etc) au préalable avant l'acceptation)

Donc : défini par le proprio.

**Comment by Ozurah** [comment]
closed by PR #42
